version: "3"
services: 
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes:
            - D:\Cursos\React\NODE-DOCKER:/app
            - /app/node_modules 
        environment: 
            - NODE_ENV=development
            - MONGO_USER=matho
            - MONGO_PASSWORD=mypassword
            - SESSION_SECRET=secret
        command: npm run dev
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=matho
            - MONGO_INITDB_ROOT_PASSWORD=mypassword